### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [php-cuong/magento2-customer-avatar#5]
Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Customer\Model\Metadata\Form\File::extractValue() must implement interface Magento\Framework\App\RequestInterface, none given, called in /opt/lampp/htdocs/magento2/vendor/magento/framework/Interception/Interceptor.php on line 58 and defined in /opt/lampp/htdocs/magento2/vendor/magento/module-customer/Model/Metadata/Form/File.php:107 Stack trace: #0 /opt/lampp/htdocs/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Customer\Model\Metadata\Form\File->extractValue() #1 /opt/lampp/htdocs/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Model\Metadata\Form\Image\Interceptor->___callParent('extractValue', Array) #2 /opt/lampp/htdocs/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Model\Metadata\Form\Image\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #3 /opt/lampp/htdocs/mij_n in /opt/lampp/htdocs/magento2/vendor/magento/module-customer/Model/Metadata/Form/File.php on line 107

**Comment by dodiya-divyarajsinh** [comment]
http://localhost/magento2/customer/account/editPost/
Magento version 2.2

**Comment by Simonchik** [comment]
https://github.com/php-cuong/magento2-customer-avatar/blob/master/Plugin/Metadata/Form/Image.php#L37 - this return does not necessary for Magento 2.2

**Comment by priyanka795** [comment]
I am having the same issue at Magento version 2.3.2

**Comment by prateekkarki** [comment]
@dodiya-divyarajsinh @Simonchik @priyanka795 
If anyone's still having the issue, update [this line](https://github.com/php-cuong/magento2-customer-avatar/blob/master/Plugin/Metadata/Form/Image.php#L37) to 

>         return [$value];
That solved it for me.

**Comment by priyanka795** [comment]
Thanks for the reply. But we remove your module.

*Thanks and Regards*

*Priyanka*
*Skype ID:psingh613*


* <https://plus.google.com/u/0/+PriyankaSingh33>
<https://www.facebook.com/33priyanka> <https://twitter.com/priyanka895509>
<https://www.linkedin.com/in/priyanka-singh-38422878/>*

**Comment by sminmlc** [comment]
Thanks prateekkarki this solution works fine!! 

> @dodiya-divyarajsinh @Simonchik @priyanka795
> If anyone's still having the issue, update [this line](https://github.com/php-cuong/magento2-customer-avatar/blob/master/Plugin/Metadata/Form/Image.php#L37) to
> 
> > ```
> >     return [$value];
> > ```
> 
> That solved it for me.
